
add_lab("UMMatrixMultiplication")
add_lab_template("UMMatrixMultiplication" ${CMAKE_CURRENT_LIST_DIR}/template.cu)
add_lab_solution("UMMatrixMultiplication" ${CMAKE_CURRENT_LIST_DIR}/solution.cu)

find_package(OpenMP)
if (OPENMP_FOUND)
    set_source_files_properties(${CMAKE_CURRENT_LIST_DIR}/template.cu PROPERTIES COMPILE_FLAGS "${COMPILE_FLAGS} -Xcompiler ${OpenMP_CXX_FLAGS} -UGPUTK_USE_CUDA")
    set_source_files_properties(${CMAKE_CURRENT_LIST_DIR}/solution.cu PROPERTIES COMPILE_FLAGS "${COMPILE_FLAGS} -Xcompiler ${OpenMP_CXX_FLAGS} -UGPUTK_USE_CUDA")
    add_lab_template_libs("UMMatrixMultiplication" OpenMP::OpenMP_CXX)
    add_lab_solution_libs("UMMatrixMultiplication" OpenMP::OpenMP_CXX)
else ()
    set_source_files_properties(${CMAKE_CURRENT_LIST_DIR}/template.cu PROPERTIES COMPILE_FLAGS "${COMPILE_FLAGS} -UGPUTK_USE_CUDA")
    set_source_files_properties(${CMAKE_CURRENT_LIST_DIR}/solution.cu PROPERTIES COMPILE_FLAGS "${COMPILE_FLAGS} -UGPUTK_USE_CUDA")
endif()
