
find_package(OpenMP)
if (OPENMP_FOUND)
    add_lab("HeatEquationMG")
    add_lab_template("HeatEquationMG" ${CMAKE_CURRENT_LIST_DIR}/template.cu)
    add_lab_solution("HeatEquationMG" ${CMAKE_CURRENT_LIST_DIR}/solution.cu)
    set_source_files_properties(${CMAKE_CURRENT_LIST_DIR}/template.cu PROPERTIES COMPILE_FLAGS "${COMPILE_FLAGS} -Xcompiler ${OpenMP_CXX_FLAGS} -UGPUTK_USE_CUDA")
    set_source_files_properties(${CMAKE_CURRENT_LIST_DIR}/solution.cu PROPERTIES COMPILE_FLAGS "${COMPILE_FLAGS} -Xcompiler ${OpenMP_CXX_FLAGS} -UGPUTK_USE_CUDA")
    add_lab_template_libs("HeatEquationMG" OpenMP::OpenMP_CXX)
    add_lab_solution_libs("HeatEquationMG" OpenMP::OpenMP_CXX)
endif()
